name: bantay_sarai
description: tool for farmers to report their crop planting date, expected harvest date, expected yield, then later on actual yield.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^3.1.1
  circular_bottom_navigation: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  cloud_firestore: ^2.5.0
  firebase_auth: ^3.0.2
  intl: ^0.17.0
  google_maps_flutter: ^2.0.6
  flutter_custom_clippers: ^2.0.0
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.9
  http: ^0.13.3

dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/rice_banner.jpg
    - assets/logos/bantay_sarai_header.png
    - assets/logos/bantay_sarai_header_white.png
    - assets/logos/dost-pcaarrd-uplb.png
    - assets/logos/sarai.png
    - assets/logos/sarai_logo.png
    - assets/images/farmer.png
    - assets/images/corn1.png
    - assets/images/rice1.png
    - assets/images/banana1.png
    - assets/images/coconut1.png
    - assets/images/cacao1.png
    - assets/images/coffee1.png
    - assets/images/soybean1.png
    - assets/images/sugarcane1.png
    - assets/images/tomato1.png
    - assets/images/corn1_light.png
    - assets/images/rice1_light.png
    - assets/images/banana1_light.png
    - assets/images/coconut1_light.png
    - assets/images/cacao1_light.png
    - assets/images/coffee1_light.png
    - assets/images/soybean1_light.png
    - assets/images/sugarcane1_light.png
    - assets/images/tomato1_light.png
    - assets/images/other crop1.png
    - assets/images/other crop1_light.png
    - assets/icons/raindrop.png
    - assets/weather_underground/0.png
    - assets/weather_underground/1.png
    - assets/weather_underground/2.png
    - assets/weather_underground/3.png
    - assets/weather_underground/4.png
    - assets/weather_underground/5.png
    - assets/weather_underground/6.png
    - assets/weather_underground/7.png
    - assets/weather_underground/8.png
    - assets/weather_underground/9.png
    - assets/weather_underground/10.png
    - assets/weather_underground/11.png
    - assets/weather_underground/12.png
    - assets/weather_underground/13.png
    - assets/weather_underground/14.png
    - assets/weather_underground/15.png
    - assets/weather_underground/16.png
    - assets/weather_underground/17.png
    - assets/weather_underground/18.png
    - assets/weather_underground/19.png
    - assets/weather_underground/20.png
    - assets/weather_underground/21.png
    - assets/weather_underground/22.png
    - assets/weather_underground/23.png
    - assets/weather_underground/24.png
    - assets/weather_underground/25.png
    - assets/weather_underground/26.png
    - assets/weather_underground/27.png
    - assets/weather_underground/28.png
    - assets/weather_underground/29.png
    - assets/weather_underground/30.png
    - assets/weather_underground/31.png
    - assets/weather_underground/32.png
    - assets/weather_underground/33.png
    - assets/weather_underground/34.png
    - assets/weather_underground/35.png
    - assets/weather_underground/36.png
    - assets/weather_underground/37.png
    - assets/weather_underground/38.png
    - assets/weather_underground/39.png
    - assets/weather_underground/40.png
    - assets/weather_underground/41.png
    - assets/weather_underground/42.png
    - assets/weather_underground/43.png
    - assets/weather_underground/44.png
    - assets/weather_underground/45.png
    - assets/weather_underground/46.png
    - assets/weather_underground/47.png
    - assets/weather_underground/na.png
  #  - images/a_dot_ham.jpeg

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/new_splash.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
